name: "CCGFW Checkin"

on:
  schedule:
    - cron: "10 16 * * *"  # scheduled at 00:10 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.16

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Cloudflare Warp
        uses: Boostport/setup-cloudflare-warp@v1.15.0
        with:
          organization: ${{ secrets.CLOUDFLARE_ORG }}
          auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

      - name: Run sign
        env:
          URL: ${{ secrets.CCGFW_URL }}
          CONFIG: ${{ secrets.CCGFW_CONFIG }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python3 ./main.py
